name: CSS Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - E2ETests
      - GitActionsE2E
      - Post-Functionality
      - SQLite
      - SQLiteV2
      - calendarDate
      - fix_SQLitexPost
      - jeff

jobs:
  validate-css:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CSS Validator
      run: npm install -g css-validator

    - name: Validate CSS files
      run: css-validator "public/styles.css"
