name: E2E Tests # name of the test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - E2ETests
      - GitActionsE2E
      - Post-Functionality
      - SQLite
      - SQLiteV2
      - calendarDate
      - fix_SQLitexPost
      - jeff

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Install Dependencies
        run: npm install
      - name: sqlite?
        run: npm install sqlite3
      - name: Start Server?
        run: node server.mjs
      - name: E2E Test
        run: npm test # the actual testing line