name: HTML Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - E2ETests
      - GitActionsE2E
      - Post-Functionality
      - SQLite
      - SQLiteV2
      - calendarDate
      - fix_SQLitexPost
      - jeff

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate HTML files
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: 'public/'


